### PR TITLE
Copyright functionality added

### PR DESCRIPTION
**Pull request by lucomsky**
#12 fix

### CODE REVIEW

**Comment by lucomsky** [comment]
@stpettersens I see some inconsistent in this repo: *.yml file missed. So I can't finish `gulp test` procedure :-( and `test/control` file should be corrected due to my changes in `description` param.

**Comment by lucomsky** [comment]
And I'll rename parameter to just "copyright" to be in your paradigm.

**Comment by stpettersens** [comment]
@lucomsky: Thank you for your PR and feedback.

I will have more time to correct any outstanding issues to integrate your changes next weekend. Since you are adding new functionality here, I think it will be best if I take my time with this, and read carefully through the documentation concerning copyright files which you have provided. This way we can be confident every works as expected.

I will leave this issue open until then.

**Comment by lucomsky** [comment]
@stpettersens, I put some additional minor functionality to install scripts' parameters. Now we can also use string with path to script as parameter that is very useful for real use. Please merge!

**Pull request merged**
