### PR TITLE
I added the architecture part in the created deb file

### PR DESCRIPTION
**Pull request by OlafRadicke**
I think that's the debian way: See examples in https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Files

### CODE REVIEW

**Comment by OlafRadicke** [comment]
Sorry, I broke the test, but I don't no why.

**Comment by OlafRadicke** [comment]
Test is fixed now.

**Comment by stpettersens** [comment]
Thank you, @OlafRadicke!

Merry Christmas.

**Comment by OlafRadicke** [comment]
You are welcome. 

Peaceful time and Happy new Year.

**Comment by stpettersens** [comment]
Same to you.

 I've published those changes as [0.1.3 on the registry](https://www.npmjs.com/package/gulp-debian). ([libraries.io](https://libraries.io/npm/gulp-debian)).

**Pull request merged**
